[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

# Optimize deps
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.6.0", features = ["dynamic"] }
rand = "0.8.4"
lazy_static = "1.4.0"
